### ISSUE TITLE
The green arrow doesn't work properly

### ISSUE THREAD

**Issue by Insane96** [gbl/EasierVillagerTrading#2]
I have the items to trade in this screenshot but the green arrow doesn't show up.
![2018-10-31_11 50 08](https://user-images.githubusercontent.com/7185104/47783955-7954ac00-dd04-11e8-82b1-c1c3a4b3f9d5.png)

**Comment by gbl** [comment]
Probably a problem with enchanted items - enchanted items are excluded from trades. Need to check if compasses are detected as "enchanted" even when they are not.

**Comment by gbl** [comment]
Can't reproduce, trading a compass works well for me. Still assuming the compass was enchanted which prevents trades.

**Comment by Insane96** [comment]
The compass was not enchanted but had some tags from Quark

**Comment by Insane96** [comment]
The check shouldn't be done with tags since vanilla seems to not care about them
