### ISSUE TITLE
Don't take effect although the mod can be loaded when Itemscroller etc. exists at the same time.

### ISSUE THREAD

**Issue by crosspedestrian** [gbl/EasierVillagerTrading#21]
How odd!
When I'm loading EasierVillagersTrading with some masa's mods, EasierVillagersTrading can be loaded but can't take effect (just same as vanilla). 

Game Verison: 1.16.5

Masa's mods I load are:  MaLiLib(pre-mod), Item Scroller, Litematica, MiniHUD and Tweakeroo.
a)  When I load MaLiLib with any one of above, EasierVillagersTrading works normal.
b)  When I load all mods except Item Scroller, EasierVillagersTrading works normal.
c)  When I load MaLiLib and Item Scroller with any one of others, EasierVillagersTrading can't work but it is loaded (appear in the modmenu mod).

Game hasn't crashed from first to last.

[minecraft-exported-logs-2021-02-21T10-48-11.log](https://github.com/gbl/EasierVillagerTrading/files/6017126/minecraft-exported-logs-2021-02-21T10-48-11.log)

**Comment by gbl** [comment]
I'm not using ItemScroller myself, but it seems that it allows you to re-sort the trades list. Which means it needs to translate "Click on row 1" to "Click on the item that was moved to row 1 by resorting". Which in turn means ItemScroller handles clicks on the trade buttons itself, which unfortunately means it "steals" clicks so my mod never sees them. Can't do much about that, sorry.
