### ISSUE TITLE
Can't Build

### ISSUE THREAD

**Issue by fooeyround** [gbl/EasierVillagerTrading#28]
I am trying to build the mod but it wont build and says it uses deprecated features for Gradle 8.0

**Comment by gbl** [comment]
I never tried Gradle 8 on it. Versions for Java 8 / MC 16 work with Gradle 4.10. the Java 16/MC 17 version works with Gradle 7.0.2.

**Comment by fooeyround** [comment]
I was not even using gradle 8  tho so idk but its fine cause I got a build from modrinth and it seemed to be latest
