### ISSUE TITLE
Add tooltips for arrow and Xs

### ISSUE THREAD

**Issue by Insane96** [gbl/EasierVillagerTrading#3]
E.g.
![2018-10-31_11 50 081](https://user-images.githubusercontent.com/7185104/47784058-c6388280-dd04-11e8-9233-c0bd9945020e.png)

**Comment by gbl** [comment]
Good idea, will probably include this when forge for MC 1.13 is done and I update the mod.

**Comment by gbl** [comment]
Included into EasierVillagerTrading 1.3
