### ISSUE TITLE
in 1.16.5 this mod fails to render a compass

### ISSUE THREAD

**Issue by fooeyround** [gbl/EasierVillagerTrading#31]
item has:
	Item Damage: 0
	Item NBT: null
	Item Foil: false

it is when I load the villager screen.
Full Crash Report:

---- Minecraft Crash Report ----
// You're mean.

Time: 9/29/21 4:21 PM
Description: Rendering item

java.lang.NullPointerException: Rendering item
	at net.minecraft.class_799.handler$baj000$matches(class_799.java:1031)
	at net.minecraft.class_799.method_3473(class_799.java:44)
	at net.minecraft.class_806.method_3495(class_806.java:50)
	at net.minecraft.class_918.method_4019(class_918.java:249)
	at net.minecraft.class_918.method_4026(class_918.java:332)
	at net.minecraft.class_918.method_27953(class_918.java:318)
	at net.minecraft.class_492.method_25394(class_492.java:217)
	at net.minecraft.class_757.method_3192(class_757.java:616)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_799.handler$baj000$matches(class_799.java:1031)
	at net.minecraft.class_799.method_3473(class_799.java:44)
	at net.minecraft.class_806.method_3495(class_806.java:50)
	at net.minecraft.class_918.method_4019(class_918.java:249)

-- Item being rendered --
Details:
	Item Type: compass
	Item Damage: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.class_918.method_4026(class_918.java:332)
	at net.minecraft.class_918.method_27953(class_918.java:318)
	at net.minecraft.class_492.method_25394(class_492.java:217)

-- Screen render details --
Details:
	Screen name: de.guntram.mcmod.easiervillagertrading.BetterGuiMerchant
	Mouse location: Scaled: (400, 221). Absolute: (1600.000000, 883.000000)
	Screen size: Scaled: (800, 442). Absolute: (3200, 1766). Scale factor of 4.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['JackMC__'/5412556, l='ClientLevel', x=-334.58, y=71.00, z=-1034.94]]
	Chunk stats: Client Chunk Cache: 4096, 1089
	Level dimension: minecraft:the_end
	Level spawn location: World: (-208,73,-224), Chunk: (at 0,4,0 in -13,-14; contains blocks -208,0,-224 to -193,255,-209), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 803234142 game time, 820513838 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 587646184 bytes (560 MB) / 1342177280 bytes (1280 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bebooks: Better Enchanted Books 1.2.9
		chime: Chime 1.1.3
		cleardespawn: Clear Despawn 1.16.5-fabric0.30.0-1.1.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.11.26
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		crowdin-translate: CrowdinTranslate 1.2
		dashloader: DashLoader 1.4.5
		easiervillagertrading: EasierVillagerTrading 1.16.5-fabric0.30.0-1.5.4
		fabric: Fabric API 0.33.0+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.6
		fancymenu: FancyMenu 2.0.5
		fiber: fiber 0.23.0-2
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		indium: Indium 1.0.0+mc1.16.5
		io_activej_activej-codegen: activej-codegen 4.2
		io_activej_activej-serializer: activej-serializer 4.2
		iris: Iris 1.0.2
		itemscroller: Item Scroller craftfix-1.2.3
		java: Java HotSpot(TM) 64-Bit Server VM 8
		konkrete: Konkrete 1.1.7
		litematica: Litematica 0.0.0-dev.20210420.200000
		malilib: MaLiLib 0.10.0-dev.21+arne.5
		minecraft: Minecraft 1.16.5
		minihud: MiniHUD 0.19.0-dev.20210215.151117
		modmenu: Mod Menu 1.16.9
		net_gudenau_lib_unsafe: unsafe 1.4.1
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		org_pircbotx_pircbotx: pircbotx 2.1
		org_slf4j_slf4j-api: slf4j-api 1.7.29
		phosphor: Phosphor 0.7.2+build.12
		quickcarpet: QuickCarpet 3.1.0
		quickcarpet-api: QuickCarpet API 1.1.0
		replaymod: Replay Mod 1.16.4-2.5.2
		slotlock: SlotLock 1.0.4.1-JBETA+1.16.5
		smoothboot: Smooth Boot 1.16.5-1.6.0
		sodium: Sodium 0.2.0+IRIS2-rev.31828aa
		syncmatica: Syncmatica 0.2.2
		tweakeroo: Tweakeroo 0.10.0-dev.20210419.180902
		twitchchat: Twitch Chat Bridge 0.10.1b
		voxelmap: VoxelMap 1.10.15
		worldedit: WorldEdit 7.2.5+57d5ac9
	Launched Version: fabric-loader-0.11.6-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon(TM) RX 550 GL version 4.6.13587 Compatibility Profile Context 19.40.38.02 26.20.14038.2009, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: replaymod_lang (incompatible), vanilla, Fabric Mods, file/Jack'sVanillaTweaks, file/Jack's Colorful Elytra, file/ItemStitchFix, file/IlmangoGoldenApples
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 1700 Eight-Core Processor

**Comment by gbl** [comment]
Must be a problem with another mod, that shows when trying to render a compass, but independent of the compass being in EVT or somewhere else. 

Rendering a compass works well in 1.16.5 with EVT enabled, no matter if it's in the inventory or a trade, see here:

![image](https://user-images.githubusercontent.com/243563/135405241-0a2718d7-75d9-4894-a10d-122891ac94a8.png)

From the stacktrace, the error is thrown at

```
at net.minecraft.class_799.handler$baj000$matches(class_799.java:1031)
at net.minecraft.class_799.method_3473(class_799.java:44)
```

where class_799 is `net/minecraft/client/render/model/json/ModelOverride` and baj000 changes the method 3473, `matches`.  Seems like some mod is checking the compass against "something" which fails. Unfortunately the stacktrace doesn't tell what that "some mod" or "something" is.

Feel free to reopen if the problem still occurs when you have nothing but EVT loaded.
