### ISSUE TITLE
Can you update this mod to mc 1.13.2?

### ISSUE THREAD

**Issue by rainchi** [gbl/EasierVillagerTrading#4]

**Comment by gbl** [comment]
There is no version of Forge for 1.13 yet, so I'm kinda stuck.

Some people have built a new modloader named Rift, but it has a lot of things that are different to Forge, so porting the mod over isn't an easy task either - I might look into that if Forge keeps us waiting, but don't expect an eta yet.

**Comment by rainchi** [comment]
Forge have 1.13 test build now
and it is almost completed 
[https://files.minecraftforge.net/maven/net/minecraftforge/test/forge/index_1.13.html](url)

**Comment by gbl** [comment]
There is a Rift version of the mod now - still in beta, and it needs a Rift feature that I sent a pull request for (adding commands to be executed on the client, not server) but which isn't in Rift yet. The maintainer of the 1.13.2 fork of Rift, Chocohead, said on Discord he will be checking out the PR.

You get the mod itself here: https://github.com/gbl/EasierVillagerTrading/releases/tag/1.3beta1
and the version of Rift that has Local Commands added here: https://github.com/gbl/Rift/releases/tag/SNAPSHOT-1.0.4.77

I'm looking forward to feedback on this.

**Comment by gbl** [comment]
A 1.13.2 version for the Rift modloader is available on CurseForge now.
