### ISSUE TITLE
mod doesn't work on 1.20

### ISSUE THREAD

**Issue by 2508932142** [gbl/EasierVillagerTrading#48]
mod doesn't work on 1.20

**Comment by Soyumo** [comment]
There is no 1.20-1.20.1 port yet

**Comment by kaerns** [comment]
Everyone here is waiting for 1.20+ support. There is already a Pull Request for it however @gbl hasn't reviewed it so far. Since this Mod is probably maintained in their free time, all we can do is wait and hope.

**Comment by gbl** [comment]
I'm currently reviewing several of my mods, this one is one of them. Expect a version in the next few days.

**Comment by gbl** [comment]
Version here and published to Modrinth and Curseforge.
