### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by i1000** [gbl/EasierVillagerTrading#6]
I am using 1.13 Rift and 1.13.2 Villager Trading Mod. Game crashes on startup every time. Is there a rift for 1.13.2 or is there a Villager Trading Mod for 1.13?

**Comment by gbl** [comment]
Rift 1.13.2 is here: https://github.com/Chocohead/Rift and the direct download link for the .jar is https://jitpack.io/com/github/Chocohead/Rift/jitpack-SNAPSHOT/Rift-jitpack-SNAPSHOT.jar - unfortunately, curseforge didn't allow me to link them directly in my description (they don't allow external download links).
