### ISSUE TITLE
Can give me the 1.13.2 beta5 version of the source code

### ISSUE THREAD

**Issue by a3539450** [gbl/EasierVillagerTrading#8]
Can give me the beta5 version of the source code

**Comment by gbl** [comment]
Sorry, seems I didn't push that. Fixed now.
Please note that you need to check out my RiftTools repository as well, and if you aren't using Linux, replace the src/main/java/de/guntram/mcmod/rifttools symlink with the contents of that repo.

**Comment by a3539450** [comment]
OK,Thank You
